services:
  frontend:
    build: ../sharealink
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"   # Linux necesita esto
    environment:
      APP_ENV: dev
      BACKEND_LOGIN_URL: "http://host.docker.internal:8081/api/v1/auth/login"
      BACKEND_URL: "http://host.docker.internal:8081"
      INTERNAL_API_URL: "http://host.docker.internal:8081"