services:
  backend:
    build: ./backend
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    #extra_hosts:
    # - "host.docker.internal:host-gateway"
    environment:
      APP_ENV: dev
      APP_SECRET: devsecret
      DATABASE_URL: "mysql://SLUser:MzQCP7PImhVhWv29Ugex8feY@mysql:3306/SLDB?serverVersion=mariadb-11.8.8&charset=utf8mb4"
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      JWT_SECRET_KEY: "/var/www/html/config/jwt/private.pem"
      JWT_PUBLIC_KEY: "/var/www/html/config/jwt/public.pem"
      JWT_PASSPHRASE: devpass
      SENTRY_DSN: ""
    entrypoint: ["/entrypoint-web.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/doc"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  worker:
    build: ./backend
    depends_on:
      backend:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_ENV: dev
      APP_SECRET: devsecret
      DATABASE_URL: "mysql://SLUser:MzQCP7PImhVhWv29Ugex8feY@mysql:3306/SLDB?serverVersion=mariadb-11.8.8&charset=utf8mb4"
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      JWT_SECRET_KEY: "/var/www/html/config/jwt/private.pem"
      JWT_PUBLIC_KEY: "/var/www/html/config/jwt/public.pem"
      JWT_PASSPHRASE: devpass
      SENTRY_DSN: ""
    entrypoint: ["/entrypoint-worker.sh"]

  mysql:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SLDB
      MYSQL_USER: SLUser
      MYSQL_PASSWORD: MzQCP7PImhVhWv29Ugex8feY
    container_name: mediabridge_mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: mediabridge_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      APP_ENV: dev
      BACKEND_LOGIN_URL: "http://backend/api/v1/auth/login"
      BACKEND_URL: "http://backend"
      INTERNAL_API_URL: "http://backend"
    entrypoint: ["/entrypoint-frontend.sh"]


#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: mediabridge_rabbitmq
#    ports:
#      - "5673:5672"
#      - "15673:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    healthcheck:
#      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
#      interval: 5s
#      timeout: 5s
#      retries: 10