[supervisord]
nodaemon=true
loglevel=info
logfile=/dev/null
logfile_maxbytes=0

[program:messenger-async]
command=php bin/console messenger:consume async -vv --time-limit=3600 --memory-limit=128M
autostart=true
autorestart=true
numprocs=1
priority=10
stopwaitsecs=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:messenger-tmdb-sync]
command=php bin/console messenger:consume tmdb_sync -vv --time-limit=3600 --memory-limit=128M
autostart=true
autorestart=true
numprocs=1
priority=20
stopwaitsecs=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0